### ISSUE TITLE
Android Error installing module

### ISSUE THREAD

**Issue by OliverTr54** [yesiman/ekoal.cdv.sumup#1]
Hello,

I wanted to inmstall your plugin today and I got an error - what's wrong?
```
An error occurred while running cordova plugin add https://github.com/yesiman/ekoal.cdv.sumup --variable SUMUP_A... (exit code 1):

        Error: Failed to fetch plugin https://github.com/yesiman/ekoal.cdv.sumup via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.

```
I need your cordova plugin urgently for my project.

Did you use it also so far in an Ionic 2 application?

Regards,
Oliver

**Comment by epicazo** [comment]
Hello Oliver,

Did you manage to make it work? 
I have to use the sumup terminal with my Ionic app but I have the same error as you did, I saw that you made some changes on the repository and tried your way but I now have an error when trying to build the application.

Cheers, Esteban.

**Comment by yesiman** [comment]
Hi
Build error can be cause by graddle configuration can you provide me the error detail

**Comment by epicazo** [comment]
When I tried to install your plugin I got this error

> Error: Failed to fetch plugin https://github.com/yesiman/ekoal.cdv.sumup via registry.
>         Probably this is either a connection problem, or plugin spec is incorrect.
>         Check your connection and plugin name/version/URL.
>         Error: npm: Command failed with exit code 235 Error output:
>         npm ERR! addLocal Could not install
>         /tmp/npm-33642-05add492/git-cache-6c0d3afe/7a422781b8084ea87889f4aa8d1cde5d55bf1a3a
>         npm ERR! Darwin 16.5.0
>         npm ERR! argv "/Users/esteban/.nvm/versions/node/v7.3.0/bin/node"
>         "/Users/esteban/.nvm/versions/node/v7.3.0/bin/npm" "install" "https://github.com/yesiman/ekoal.cdv.sumup"
>         "--save"
>         npm ERR! node v7.3.0
>         npm ERR! npm  v3.10.10
>         npm ERR! code EISDIR
>         npm ERR! errno -21
>         npm ERR! syscall read
>         
>         npm ERR! eisdir EISDIR: illegal operation on a directory, read
>         npm ERR! eisdir This is most likely not a problem with npm itself
>         npm ERR! eisdir and is related to npm not being able to find a package.json in
>         npm ERR! eisdir a package you are trying to install.

After trying to find how to fix it, I went on Oliver's github page and saw that he made some modifications, and added a package.json and updated some files, this fixed the installation of the plugin. However now I'm getting an error when doing: ionic cordova build android and get this : 

Error: /Applications/MAMP/htdocs/sumUp/platforms/android/gradlew: Command failed with exit code 1 Error output:
        

> /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:16: error: package
>         com.sumup.merchant.api does not exist
>         import com.sumup.merchant.api.SumUpAPI;
>         ^
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:17: error: package
>         com.sumup.merchant.api does not exist
>         import com.sumup.merchant.api.SumUpPayment;
>         ^
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:18: error: package
>         com.sumup.merchant.api does not exist
>         import com.sumup.merchant.api.SumUpState;
>         ^
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:31: error: cannot find
>         symbol
>         SumUpState.init(cordova.getActivity());
>         ^
>         symbol: variable SumUpState
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:42: error: cannot find
>         symbol
>         SumUpPayment payment = SumUpPayment.builder()
>         ^
>         symbol:   class SumUpPayment
>         location: class sumup
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:47: error: package
>         SumUpPayment does not exist
>         .currency(SumUpPayment.Currency.valueOf(args.get(1).toString()))
>         ^
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:45: error: package R
>         does not exist
>         .affiliateKey(this.cordova.getActivity().getString(R.string.SUMUP_API_KEY))
>         ^
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:42: error: cannot find
>         symbol
>         SumUpPayment payment = SumUpPayment.builder()
>         ^
>         symbol:   variable SumUpPayment
>         location: class sumup
>         /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/sumup/sumup.java:62: error: cannot find
>         symbol
>         SumUpAPI.openPaymentActivity(this.cordova.getActivity(), payment, 1);
>         ^
>         symbol:   variable SumUpAPI
>         location: class sumup
>         Note: /Applications/MAMP/htdocs/sumUp/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java
>         uses or overrides a deprecated API.
>         Note: Recompile with -Xlint:deprecation for details.
>         9 errors
>         
>         FAILURE: Build failed with an exception.
>         
>         * What went wrong:
>         Execution failed for task ':compileDebugJavaWithJavac'.
>         > Compilation failed; see the compiler error output for details.

I tried to look into the files of the plugin when I'm a noob when it comes to Java but from what I understand the sumup.java can't find where to find the classes SumUpAPI, SumUpPayment, SumUpState when they are present in the  merchant-sdk-2.3.0.aar...

I'm clueless on how to resolve this. Sorry for my english, I hope I made myself clear.
Thanks.

**Comment by yesiman** [comment]
Hi
I don't know what oliver made he should submit the modifications to me instead of duplicate project.
For your error i think the sumup framework has not been installed properly, can you verify your graddle file for these keys :

`repositories {
        mavenCentral()
        jcenter()
    }`

`allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.sumup.com/releases' }
    }
}`

`dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
  compile('com.sumup:merchant-sdk:1.55.1@aar') {
    transitive = true
  }
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    // SUB-PROJECT DEPENDENCIES END
}`

**Comment by OliverTr54** [comment]
Hi @ all,

I was just trying to update the SDK and a JS file to use with Ionic 3, but it did not work out... but I needed to create a fork for the Ionic packaging... anyway - I did not succeed so far. Just tons of errors:(

**Comment by yesiman** [comment]
Hi
I've just installed plugin on a v2 ionic test app and installation works fine.
Builds error (ion cbuild android) on android are because of the non presence of the sdk. 
Try modifying in android studio your graddle file or include it in your project.

**Comment by OliverTr54** [comment]
Could you please submit a fully working plugin... I don't really code with Android Studio and I have to use the Ionic packager...

**Comment by yesiman** [comment]
@epicazo can you try with sumup sdk v1.55 .

**Comment by epicazo** [comment]
@yesiman I don't know what you're trying to tell me, I can't install the plugin from your repository as its missing the package.json file. See my post above the error I'm getting.

The graddle file you asked me to check is the one located in /platforms/android/build.graddle ? It's generated automatically when building the platform right? If so I should modify it in order to match what you've write above?

maybe it's a long shot but seeing your name and location, maybe you speak french? i may understand you better

**Comment by yesiman** [comment]
Si tu parles Français : 
Cette erreur (entre autre) : com.sumup.merchant.api does not exist est due au fait que le SDK Sumup n'est pas ajouté dans les dépendances. Donc peu etre tester en l'ajoutant directement dans Android studio.
Ce plugin a été testé sur le framework 1.55 sur android et apple il y a 6 mois et fonctionait pour l'authentification et le paiement.

**Comment by epicazo** [comment]
Je n'ai peut être pas été assez clair dans mes explications, je n'arrive pas a installer ton plugin, j'obtiens cette erreur : 

> Error: Failed to fetch plugin https://github.com/yesiman/ekoal.cdv.sumup via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: npm: Command failed with exit code 235 Error output:
> npm ERR! addLocal Could not install /tmp/npm-41746-6e81b7fc/git-cache-991718ba/7a422781b8084ea87889f4aa8d1cde5d55bf1a3a
> npm ERR! Darwin 16.5.0
> npm ERR! argv "/Users/esteban/.nvm/versions/node/v7.3.0/bin/node" "/Users/esteban/.nvm/versions/node/v7.3.0/bin/npm" "install" "https://github.com/yesiman/ekoal.cdv.sumup" "--save"
> npm ERR! node v7.3.0
> npm ERR! npm  v3.10.10
> npm ERR! code EISDIR
> npm ERR! errno -21
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Applications/MAMP/htdocs/sumUp/node_modules/npm-debug.log

Donc comment se fait-il que tu ai réussi a l'installer sous ionic v2? Mon projet est sous Ionic v1 mais j'ai essayé avec un projet v2 et j'ai la meme erreur. Pour ce qui est de l'erreur du sdk sumup et des dépendance, il se peut que Oliver ai mal configuré des fichiers et que ça ne soit pas le seul probleme.

Désolé pour les questions

**Comment by OliverTr54** [comment]
I think my is now working for Android - I was just able to compile, but not able to test it with the SumUp terminal. I don't have it with me at the moment. I will also work now on the IOS sources.

...at least the "ionic package build android" was not throwing any errors anymore.

**Comment by yesiman** [comment]
Nice, on IOS it was very easy but Android very difficult...Dependencies on IOS should be installed automatically, but i don't understant why you need a package.json file for plugin installation. 
On your device when you call method you should see a screen for sumup authentification and device pairing.

**Comment by yesiman** [comment]
@epicazo Quel language/techno tu utilises ? Le chemin "Applications/MAMP/htdocs" est bizarre pour une installation de plugin.

**Comment by epicazo** [comment]
@yesiman Je dev avec le framework ionic, j'utilise la console pour l'installation des plugins. Mon chemin est juste celui ou se trouve le repertoire de mon application, ça n'a pas grande importance. J'utilise le terminal et en executant la commande pour installer le plugin comme j'ai l'habitude de faire (cordova plugin add https://github.com/yesiman/ekoal.cdv.sumup --variable SUMUP_API_KEY=YOUR_AFFILIATION_KEY) et ça me remonte l'erreur que je t'ai copié dans mon post juste au dessus, comment fait tu de ton côté ?

@OliverTr54 I tried with your update, I don't have error when building anymore but the app crash when I launch it :/

**Comment by OliverTr54** [comment]
@epicazo Do you get some message...?

**Comment by epicazo** [comment]
@OliverTr54 Just an plain alert box when I launch the app which says that the app crashed. You don't need the sumUp terminal to try that, just build and run your app on your phone

**Comment by OliverTr54** [comment]
I just updated the SDK - but none of the java files of yesiman.

**Comment by yesiman** [comment]
Windows 10 Android platform deploy
5 minutes install

### CREATING NEW IONIC PROJECT
`D:\_DEV\__CURRENT\__test>$ ionic start testsum
Creating an Ionic app in D:\_DEV\__CURRENT\__test\testsum based on the tabs template.
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip`
...
### ADDING SUMUP PLUGIN
`$ cordova plugin add https://github.com/yesiman/ekoal.cdv.sumup --variable SUMUP_API_KEY=YOUR_AFFILIATION_KEY` (bad affiliation key for test.)

### LISTING IONIC PLUGINS
`$ ionic plugin list`
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
**cordova-plugin-sumup 0.0.1 "Sumup"**
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

### ADDING ANDROID PLATFORM
ionic platform add android

### BUILD FOR ANDROID
`ionic build android`

Error -> Because of SDK miss

### Opening android project in android Studio and wait for graddle sdk updates downloads

Error in namespace to correct (app namespace) -> ok : 
`import com.ionicframework.YOUR NAMESPACE.MainActivity;`
Error in sdk

add on 'R.string.SUMUP_API_KEY" ctrl+space to link correct intellisence library.

### Sumup Errors are always present GRADDLE IS THE PROBLEM

in build.graddle

add `maven { url 'https://maven.sumup.com/releases' }` in allprojects {
    repositories {}}

add `
packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
` at the end of android {} 

add 
`compile('com.sumup:merchant-sdk:1.55.1@aar') {
    transitive = true
  }`
in dependencies

### SYNC GRADDLE for SDK download

### BUILD FOR ANDROID
`ionic build android`

`BUILD SUCCESSFUL

Total time: 37.431 secs

Built the following apk(s):
        D:/_DEV/__CURRENT/__test/testsum/platforms/android/build/outputs/apk/android-debug.apk`

OK all is runnung fine all you have to is adding js methods as mentioned in project page and call them

**Comment by yesiman** [comment]
If i have time i will automatize graddle implentation during plugin installation

**Comment by epicazo** [comment]
@yesiman Merci beaucoup pour ces explications, cela résout mes problemes et j'arrive à build l'application. Aurait tu un sample du code que tu utilises pour faire fonctionner la connexion au terminal ainsi que le paiement? 
Je suis sous angular 1 et j'ai donc utilisé ce que tu as mis dans le read.me, j'ai 2 boutons qui executent la fonction log et la fonction pay que tu fournis, la fonction log me renvoie une invalid action, et quand je clic sur pay cela m'ouvre une fenetre sumup où je me log mais ensuite l'application crash... Cela est peut etre due au fait que le téléphone n'est pas bien connecté au terminal vu que je n'ai aucune info savoir s'il est connecté ou non.

Merci en tout cas pour ton aide.

**Comment by yesiman** [comment]
Pas de soucis, j'essaie trouver un peu de temps par ci par la pour répondre ... 
Peux etre tu sais déja tout ca mais de mémoire ce qui peut merder avec sumup :
- ajouter les droits pour geolocalisation
- définir la clé d'aafiliation correcte définir dans le compte sumup
- attribuer dans le compte développeur le namespace de l'application pour l'authoriser

J'ai vraiment galéré pour créer ce plugin non pas a cause du code natif mais a cause du sdk sumup qui sous android etait particulièrement pourri et complexe a faire fonctionner (sur ios c'était simple).

Une autre chose peut causer cela sumup a mis a jour son sdk et a peut etre verouille l'accès a des sdk antérieurs (juste une idée), dans ce cas, tu as toutes les bases pour utiliser le nouveau sdk et je peux t'aider si besoin et si j'ai du temps.

Pour le code je pense que l'appel a la méthode pay sui t'affiche le login est correct, reste a comprendre pourquoi il plante après, vvela peut etre du aussi a une "activity" manquante dans le manifest :
`<activity android:label="SumUp Payment Action" android:name="org.apache.cordova.sumup.suPActivity">
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
        <activity android:label="SumUp Payment Result" android:name="org.apache.cordova.sumup.suPResultActivity">
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
        <activity android:label="Payment Result" android:name="ResultActivity">
            <intent-filter>
                <action android:name="com.example.ResultActivity" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>`

**Comment by epicazo** [comment]
@yesiman Merci j'ai reussi a le faire fonctionner sur android, du moins le paiement, j'ai aussi complété le sdk pour pouvoir faire la fonction de log même si je ne sais pas trop comment elle fonctionne pour le moment.  Ces problemes m'ont auront au moins permis de mieux comprendre comment utiliser un sdk pour cordova (meme si je serai incapable de faire ça de A à Z pour le moment)
Maintenant je suis sur iOS et j'ai une erreur qui s'affiche dans xCode quand je veux executer ma method pay, te souviens tu avoir fait quelque chose en particulier ? Je ne connais pas du tout l'environnement de dev d'apple donc c'est embetant pour modifier des trucs.

@OliverTr54 I managed to make it work on android, just follow the steps provided above by @yesiman and just change "com.sumup:merchant-sdk:1.55.1@aar" to "com.sumup:merchant-sdk:2.3.0@aar" and you should be g2g. 
Also add this to in /platforms/android/src/org/apache/cordova/sumup/sumup.java: 
```
if (action.equals("log")){
            SumUpLogin sumUplogin = SumUpLogin.builder(this.cordova.getActivity().getString(cordova.getActivity().getResources().getIdentifier("SUMUP_API_KEY", "string", cordova.getActivity().getPackageName()))).build();
            SumUpAPI.openLoginActivity(this.cordova.getActivity(), sumUplogin, 1);
            return true;
        }
```
So you can have the log method available.

**Comment by yesiman** [comment]
En fait la méthode log n'était disponible auparavant que sur android sur ios il suffit d'appeler le paiement je suppose que sumup en a fait de meme pour android ce qui n'est pas plus mal.
Pour IOS je teste dès que possible. Si tu as des infos sur l'erreur n'hésites pas.

**Comment by yesiman** [comment]
I close this issue, i open another for IOS installation #2
